## SGD classifier

In [1]:
# imports
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import re
import math
import numpy as np
from numpy import nan
import os
from pprint import pprint
import pickle

import gensim as ge
import nltk
import matplotlib.pyplot as plt

from tqdm import tqdm
tqdm.pandas()
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True, nb_workers= 16, verbose = 0)

In [2]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn import metrics

import seaborn as sns
import matplotlib.pyplot as plt

## preprocess train dataset

In [3]:
#define connection to db 
connect_string = 'postgresql+psycopg2://postgres:5050@localhost:5432/postgres'
#define sql queries
sql_query_agro = 'SELECT * FROM publ.corpus_keywords_agro'
sql_query_mesh = 'SELECT * FROM publ.corpus_keywords_mesh'
sql_query_class = 'SELECT dbrecordid, class FROM ke_stage.corpus_small'
#create engine
engine = create_engine(connect_string)
#read data as df
df_agro = pd.read_sql(sql_query_agro, engine)
df_mesh = pd.read_sql(sql_query_mesh, engine)
df_class = pd.read_sql(sql_query_class, engine)

In [4]:
#merge the ids 
def join_id(df):
    value = df['id1'].fillna(df['id2'])
    df['id1'] = value
    df = df.drop(['id2'], axis=1)
    return df

In [5]:
df_agro = join_id(df_agro)
df_mesh = join_id(df_mesh)

In [6]:
#merge both df (agrovoc and mesh)
result = pd.merge(df_agro, df_mesh, on=['id1'], how='outer')
#create list of all keywords for each document
result['keywords'] = result.apply(lambda row: [val for val in row if isinstance(val, list)], axis=1)
result = result.rename(columns={'id1':'dbrecordid'})

temp_list =  []
for row in result['keywords']:
    keywords_list = []
    for l in row:
        keywords_list.extend(l)
    for x in range(len(keywords_list)):
        keywords_list[x] = keywords_list[x].lower()
    temp_list.append(keywords_list)
    
result['keywords_all'] = temp_list

In [7]:
def combine_tokens(df):
    df['combined'] = df['keywords_all'].apply(lambda x: ','.join(x) if isinstance(x, list) else '')
    return df

In [8]:
combine_tokens(result)

dbrecordid   agro_title  \
0                                            1066854         None   
1                                            1066982  [Caribbean]   
2                                            1067820     [growth]   
3                                            1067917         None   
4                                            1068740         None   
...                                              ...          ...   
478532                                     M35209048          NaN   
478533                                     M31743057          NaN   
478534                                     M33473396          NaN   
478535  BASE::ftwhoiris:oai:apps.who.int:10665/43779          NaN   
478536                                     M29367276          NaN   

                                                 agro_abs  \
0                                         [history, game]   
1       [Netherlands (Kingdom of the), Caribbean, Cari...   
2                                          [China, China]   
3                                   [history, physicians]   
4       [living standards, towns, Syrian Arab Republic...   
...                                                   ...   
478532                                                NaN   
478533                                                NaN   
478534                                                NaN   
478535                                                NaN   
478536                                                NaN   

                                               mesh_title  \
0                                            [Life, Life]   
1                    [Caribbean Region, Caribbean Region]   
2                                        [Growth, Growth]   
3                                                    None   
4                                                    None   
...                                                   ...   
478532  [In Vitro Techniques, In Vitro Techniques, Cos...   
478533  [Chorioretinitis, Lupus Erythematosus, Systemi...   
478534     [Genome, Mitochondrial, Genome, Mitochondrial]   
478535  [Research Report, Research Report, Referral an...   
478536  [Social Control, Formal, Prostatic Neoplasms, ...   

                                                 mesh_abs  \
0       [Books, Books, Saskatchewan, Saskatchewan, Sas...   
1       [Netherlands Antilles, Suriname, Caribbean Reg...   
2                            [China, China, China, China]   
3       [Hemorrhage, Hemorrhage, Drawing, Risk, Risk, ...   
4       [Ribs, Commerce, Commerce, Ribs, Economics, Sy...   
...                                                   ...   
478532                                               None   
478533                                               None   
478534                                               None   
478535                                               None   
478536                                               None   

                                                 keywords  \
0       [[history, game], [Life, Life], [Books, Books,...   
1       [[Caribbean], [Netherlands (Kingdom of the), C...   
2       [[growth], [China, China], [Growth, Growth], [...   
3       [[history, physicians], [Hemorrhage, Hemorrhag...   
4       [[living standards, towns, Syrian Arab Republi...   
...                                                   ...   
478532  [[In Vitro Techniques, In Vitro Techniques, Co...   
478533  [[Chorioretinitis, Lupus Erythematosus, System...   
478534   [[Genome, Mitochondrial, Genome, Mitochondrial]]   
478535  [[Research Report, Research Report, Referral a...   
478536  [[Social Control, Formal, Prostatic Neoplasms,...   

                                             keywords_all  \
0       [history, game, life, life, books, books, sask...   
1       [caribbean, netherlands (kingdom of the), cari...   
2       [growth, china, china, growth, growth, china, ...   
3       [history, physicians, hemorrh

In [9]:
final_df = pd.merge(result, df_class, on=['dbrecordid'], how='inner')

In [10]:
final_df = final_df[final_df['class'] != 'Rest']

In [11]:
final_df

dbrecordid    agro_title  \
0                                            1066854          None   
4                                            1068740          None   
6                                            1070714  [provenance]   
8                                            1071537   [neoplasms]   
16                                           1078941          None   
...                                              ...           ...   
478532                                     M35209048           NaN   
478533                                     M31743057           NaN   
478534                                     M33473396           NaN   
478535  BASE::ftwhoiris:oai:apps.who.int:10665/43779           NaN   
478536                                     M29367276           NaN   

                                                 agro_abs  \
0                                         [history, game]   
4       [living standards, towns, Syrian Arab Republic...   
6       [tricarboxylic acid cycle, longevity, organism...   
8       [individuals, elderly, hormonal control, metab...   
16      [towns, drinking water, towns, towns, towns, b...   
...                                                   ...   
478532                                                NaN   
478533                                                NaN   
478534                                                NaN   
478535                                                NaN   
478536                                                NaN   

                                               mesh_title  \
0                                            [Life, Life]   
4                                                    None   
6                                                    None   
8       [Neoplasms, Neoplasms, Testis, Hormones, Hormo...   
16         [Socioeconomic Factors, Socioeconomic Factors]   
...                                                   ...   
478532  [In Vitro Techniques, In Vitro Techniques, Cos...   
478533  [Chorioretinitis, Lupus Erythematosus, Systemi...   
478534     [Genome, Mitochondrial, Genome, Mitochondrial]   
478535  [Research Report, Research Report, Referral an...   
478536  [Social Control, Formal, Prostatic Neoplasms, ...   

                                                 mesh_abs  \
0       [Books, Books, Saskatchewan, Saskatchewan, Sas...   
4       [Ribs, Commerce, Commerce, Ribs, Economics, Sy...   
6       [Lipid Metabolism, Comprehension, Quality Cont...   
8       [Aged, Nuclear Family, Nuclear Family, Risk, R...   
16      [Socioeconomic Factors, Cities, Socioeconomic ...   
...                                                   ...   
478532                                               None   
478533                                               None   
478534                                               None   
478535                                               None   
478536                                               None   

                                                 keywords  \
0       [[history, game], [Life, Life], [Books, Books,...   
4       [[living standards, towns, Syrian Arab Republi...   
6       [[provenance], [tricarboxylic acid cycle, long...   
8       [[neoplasms], [individuals, elderly, hormonal ...   
16      [[towns, drinking water, towns, towns, towns, ...   
...                                                   ...   
478532  [[In Vitro Techniques, In Vitro Techniques, Co...   
478533  [[Chorioretinitis, Lupus Erythematosus, System...   
478534   [[Genome, Mitochondrial, Genome, Mitochondrial]]   
478535  [[Research Report, Research Report, Referral a...   
478536  [[Social Control, Formal, Prostatic Neoplasms,...   

                                             keywords_all  \
0       [history, game, life, life, books, books, sask...   
4       [living standards, towns, syrian arab republic...   
6       [provenance, tricarboxylic acid cycle, longevi...   
8       [neoplasms, indiv

In [12]:
x = final_df['combined']
y = final_df['class']

In [13]:
#split into train and test data
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25)

## train model SGD

In [15]:
sgd_model = Pipeline([
                ('vect', CountVectorizer(lowercase=False,stop_words=None,tokenizer=None)),
                ('tfidf', TfidfTransformer(use_idf=True,norm="l2")),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',
                                        alpha=1e-3, random_state=42,
                                        max_iter=5, tol=None))
   ])

In [16]:
sgd_model.fit(x_train, y_train)

Pipeline(steps=[('vect', CountVectorizer(lowercase=False)),
                ('tfidf', TfidfTransformer()),
                ('clf',
                 SGDClassifier(alpha=0.001, max_iter=5, random_state=42,
                               tol=None))])

In [17]:
y_pred = sgd_model.predict(x_test)

In [18]:
print("Confusion Matrix")
matrix = metrics.confusion_matrix(y_test, y_pred)
print(matrix)

Confusion Matrix
[[14303  2450  5297  2475]
 [ 1863 16766  1791  3658]
 [ 1955  2334 19141   686]
 [ 1057  1440   659 20861]]


In [20]:
f1_matrix = metrics.classification_report(y_test, y_pred, target_names=['Medizin', 'Landwirtschaft','Umweltwissenschaften','Ernährung'], output_dict=True)
f1_matrix = pd.DataFrame(f1_matrix).transpose()
#f1_matrix.to_csv("sgd_score_cvs\F1_matrix_"+str(size)+".csv")

In [21]:
f1_matrix

precision    recall  f1-score      support
Medizin                0.745802  0.583201  0.654555  24525.00000
Landwirtschaft         0.729274  0.696320  0.712416  24078.00000
Umweltwissenschaften   0.711879  0.793705  0.750569  24116.00000
Ernährung             0.753649  0.868593  0.807049  24017.00000
accuracy               0.734690  0.734690  0.734690      0.73469
macro avg              0.735151  0.735455  0.731147  96736.00000
weighted avg           0.735179  0.734690  0.730753  96736.00000

In [22]:
# Accuracy of the model
accuracy = metrics.accuracy_score(y_test, y_pred)
print('SGD Classifier Accuracy of the model: {:.2f}%'.format(accuracy*100))

SGD Classifier Accuracy of the model: 73.47%
